#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: admin200
#  jpa:
#    hibernate.ddl-auto : create
#    generate.ddl: true
#    allow-sql: true